
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: virtualmachines.onecloud.yunion.io
spec:
  group: onecloud.yunion.io
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    singular: virtualmachine
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VirtualMachine is the Schema for the virtualmachines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VirtualMachineSpec defines the desired state of VirtualMachine
          properties:
            autoRenew:
              description: AutoRenew indicates whether to automatically renewal.
              type: boolean
            billDuration:
              description: BillDuration describes the duration of the annual and monthly
                billing type. That length of BillDuration represents the billing type
                is 'prepaid'.
              type: string
            description:
              type: string
            eip:
              description: Eip indicates that bind the existing EIP with VM. It conflicts
                with NewEip.
              type: string
            keyPairId:
              type: string
            name:
              description: Name of virtual machine
              type: string
            nameCheck:
              description: Don't check name if IgnoreName is set true
              type: boolean
            newEip:
              description: NewEip indicates that create a new EIP and bind it with
                VM. It conflicts with Eip.
              properties:
                Bw:
                  description: Bw indicates the bandwidth of the Elastic Public IP.
                  format: int64
                  minimum: 1
                  type: integer
                chargeType:
                  description: The charge type of Elastic Public IP
                  type: string
              type: object
            password:
              type: string
            projectConfig:
              properties:
                project:
                  type: string
                projectDomain:
                  type: string
              required:
              - project
              type: object
            recreatePolicy:
              description: RecreatePolicy describe that when the virtual machine is
                abnormal, how to deal with it, specifically determine whether to delete
                and recreate.
              properties:
                allways:
                  type: boolean
                matchStatus:
                  items:
                    type: string
                  type: array
                maxTimes:
                  format: int32
                  type: integer
                never:
                  type: boolean
              required:
              - maxTimes
              type: object
            resetPassword:
              type: boolean
            secgroups:
              items:
                type: string
              minItems: 1
              type: array
            vmConfig:
              properties:
                dataDisks:
                  description: DataDisks describes the configuration of data disks
                  items:
                    properties:
                      driver:
                        description: Driver represents the drive method of the disk
                          on the virtual machine.
                        enum:
                        - virtio
                        - ide
                        - scsi
                        - sata
                        - pvscsi
                        type: string
                      image:
                        description: The disk will be created from the image represented
                          by ImageId.
                        type: string
                      sizeGB:
                        description: 'SizeGB represents the size(unit: GB) of disk.'
                        format: int64
                        type: integer
                      storageConfig:
                        properties:
                          backend:
                            description: Backend represents backend of storage
                            type: string
                          medium:
                            description: StorageMedium represents storage media type
                            enum:
                            - rotate
                            - ssd
                            - hybrid
                            type: string
                          storage:
                            description: Storage represents specific storage
                            type: string
                        type: object
                    type: object
                  maxItems: 7
                  type: array
                hypervisor:
                  type: string
                instanceType:
                  description: InstanceType describes the specifications of the virtual
                    machine, which are predefined by the cloud provider. It conflicts
                    with VcpuCount and VmemSizeGB.
                  type: string
                networks:
                  items:
                    properties:
                      address:
                        type: string
                      network:
                        type: string
                    required:
                    - network
                    type: object
                  type: array
                preferHost:
                  description: PreferHost is the parameter passed to the scheduler
                    which makes the machine created in the preferred host.
                  type: string
                preferManager:
                  description: PreferManager is the parameter passed to the scheduler
                    which makes the virtual machine created in the preferred cloud
                    provider.
                  type: string
                preferRegion:
                  description: PreferRegion is the parameter passed to the scheduler
                    which makes the virtual machine created in the preferred cloud
                    region.
                  type: string
                preferWire:
                  description: PreferWire is the parameter passed to the scheduler
                    which makes the machine created in the preferred wire.
                  type: string
                preferZone:
                  description: PreferZone is the parameter passed to the scheduler
                    which makes the virtual machine created in the preferred cloud
                    zone.
                  type: string
                rootDisk:
                  description: RootDisk describes the configuration of the system
                    disk
                  properties:
                    driver:
                      description: Driver represents the drive method of the disk
                        on the virtual machine.
                      enum:
                      - virtio
                      - ide
                      - scsi
                      - sata
                      - pvscsi
                      type: string
                    image:
                      description: The disk will be created from the image represented
                        by ImageId.
                      type: string
                    sizeGB:
                      description: 'SizeGB represents the size(unit: GB) of disk.'
                      format: int64
                      type: integer
                    storageConfig:
                      properties:
                        backend:
                          description: Backend represents backend of storage
                          type: string
                        medium:
                          description: StorageMedium represents storage media type
                          enum:
                          - rotate
                          - ssd
                          - hybrid
                          type: string
                        storage:
                          description: Storage represents specific storage
                          type: string
                      type: object
                  type: object
                vcpuCount:
                  description: VcpuCount represents the number of CPUs of the virtual
                    machine. It conflicts with InstanceType and it is It is required
                    if InstanceType is not specified.
                  format: int64
                  minimum: 1
                  type: integer
                vmemSizeGB:
                  description: VmemSizeGB represents the size of memory of the virtual
                    machine. It conflicts with InstanceType and it is It is required
                    if InstanceType is not specified.
                  format: int64
                  type: integer
              required:
              - rootDisk
              type: object
          required:
          - projectConfig
          - vmConfig
          type: object
        status:
          description: VirtualMachineStatus defines the observed state of VirtualMachine
          properties:
            createTimes:
              description: CreateTimes record the continuous creation times.
              format: int32
              type: integer
            externalInfo:
              properties:
                action:
                  description: Action indicate the latest action for external vm.
                  type: string
                eip:
                  type: string
                id:
                  type: string
                ips:
                  items:
                    type: string
                  type: array
                status:
                  type: string
              type: object
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
            reason:
              description: A human readable message indicating details about why vm
                is in this phase.
              type: string
          required:
          - createTimes
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
